# Site settings
lang: en-US
title: Logan Teder
email: l.teder@columbia.edu
description: Cyberspace
baseurl: # the optional subpath of your site, e.g. "/blog"
url: loganteder.com
author:
  name: Logan Teder
  picture:
logo: /assets/log.jpg
github_username: LTeder

# Search settings
search: # true, false (default)
search_full_content: false # true, false (default)
search_provider: # lunr (default), algolia
algolia:
  application_id: # YOUR_APPLICATION_ID
  index_name: # YOUR_INDEX_NAME
  search_only_api_key: # YOUR_SEARCH_ONLY_API_KEY
  powered_by: # true (default), false

# Build settings
markdown: kramdown
remote_theme: mmistakes/jekyll-theme-basically-basic@1.4.5
plugins: # previsously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
#paginate: 10
#paginate_path: /page:num/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME
  - README.md

# Front Matter Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      read_time: true
